Terminado capítulo de estado del arte 🎨
danigonzser/proyecto-tfg pull request #11
Opened 2024-02-06 11:26 UTC by danigonzser

2024-02-06 11:58 UTC, JJ commented
El ámbito del PR tienes que declararlo en el PR; en cada PR debe haber un ámbito claramente limitado, porque si no puede acabar abarcando toda la memoria y el código.

2024-03-13 10:04 UTC, JJ requested changes
Estoy viendo que me quedaban unos cambios por subir, dale una vuelta y luego miro el resto.

2024-03-14 10:05 UTC, JJ requested changes
Deberías tratar de hacer PRs un poco más concretos, que no incluyan tanto la infraestructura como el contenido, porque si la infraestructura está bien, el resto puede bloquearlo. Yo sacaría de aquí la parte de la infraestructura, que no parece que tenga ningún problema, y dejaría la del estado del arte para más adelante.

2024-03-14 10:05 UTC, JJ commented on doc/secciones/02_estado_del_arte.tex
> +    Almacenamiento gratuito & 5 GB \\
No sé si te merece la pena comparar por cantidad de almacenamiento gratuito. ¿Vas a ofrecer tú almacenamiento gratuito?

2024-03-14 10:05 UTC, JJ commented on doc/secciones/02_estado_del_arte.tex
> +Después del estudio del panorama actual relacionado con el almacenamiento online de contenido digital, se ha identificado el problema de la inexistencia de un sistema centralizado que permita a los u
¿... y gratuita?

El estado del arte tal como lo has enfocado incluye solo soluciones comeraciales, pero no software libre. Es muy difícil competir con las soluciones comerciales, y de hecho no sé si en el proyecto vas a plantear la posible comercialización (sería una HU específica, con la posible monetización). En todo caso deberías tener una SoA mucho más estrecha, dedicada solo y exclusivamente al almacenamiento, creación y edición de memes...

2024-03-15 11:19 UTC, danigonzser commented
Perdón, no sé porqué puse lo de revisión en un issue @JJ

2024-03-15 11:25 UTC, JJ requested changes
No acabo de ver que estés reflejando correctamente el concepto de estado del arte, que no se trata de un conjunto de aplicaciones, comerciales o libres, con una vaga relación con la tuya, sino posibles competidores comerciales o de software libre que hagan algo parecido y que, en el caso de software libre, puedas reaprovechar o reusar.
Te propongo dejar esto hasta más adelante, cuando la aplicación esté bien configurara y puedas realmente comparar con lo que *has hecho*. Si te parece bien, cambia el PR y los issues correspondientes de milestone, y ponlos mucho más adelante.

2024-03-15 11:25 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En el ámbito del almacenamiento online de software libre, se encuentran diversas soluciones que abordan la gestión de contenido digital.
¿Tú vas a hacer un sistema de almacenamiento online? ¿Eso es lo que quieren tus clientes? ¿Si sacaras tu producto, estarían compitiendo con estos?

2024-03-15 11:25 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
> +En respuesta a la carencia identificada en las soluciones actuales de almacenamiento en la nube, se propone el desarrollo de una solución integral que aborde diversas necesidades no cubiertas por las
Tú no vas a proponer un sistema de almacenamiento en la nube, sino un sistema de creación y almacenamiento de memes. Como tal, podrá usar alguno de estos sistemas, es decir, podrá ser un plugin o workflow de owncloud, o bien usar un sistema totalmente diferente.

2024-04-02 08:52 UTC, JJ commented
Por favor, pon también en el cuerpo del PR de qué se trata

2024-04-16 21:51 UTC, danigonzser commented
Si de esta rama parten tanto #14 como #26, ¿hago un rebase para que se pueda retomar más adelante el estado del arte? @JJ

2024-04-22 16:40 UTC, merged