Añadido workflow para la comprobación gramatical, ortográfica y del linter de la memoria en LaTeX
danigonzser/proyecto-tfg pull request #12
Opened 2024-02-06 13:08 UTC by danigonzser

2024-02-06 18:45 UTC, JJ commented
Ahora tienes que añadir el workflow donde lo tengas aquí...

2024-02-07 08:35 UTC, JJ requested changes
A ver, varias cosas
1. El primer job no lo necesitas, simplemente porque no tienes jobs paralelos. Ese se encarga de mirar si alguno ha fallado y cortar el resto.
2. Mira a ver cuál es la última versión de `actions/checkout` y úsala
3. No sé si es buena idea usar un runner de ubuntu con una versión específica. Es mejor que  mires como se especifica "la última versión" y lo uses.
4. En cuanto a la especificación de cuando tiene que lanzarse, lo estás especificando pro ramas, lo que no sé si sería necesario. ¿Para qué quieres lanzarlo con PRs, si los PRs los vas a abrir nada más que tú, en principio? ¿No será mejor que se lance cuando se haga push a cualquier rama? Por otro lado, eso va a lanzar el comprobador gramatical cuando haya en el push *cualquier cosa*. ¿No será conveniente que se lance solo cuando se modifique algo de lo que haya que comprobar la gramática?

2024-02-07 12:10 UTC, JJ commented
En la mayor parte de los mensajes de commit haces referencia al propio PR. Deberías siempre hacer referencia al issue con el que estés trabajando, porque *siempre* hay que añadir valor al cliente.
Puede haber casos excepcionales (por ejemplo, un error ortográfico) en que sea adecuado referirse al propio PR, pero en ese caso lo correcto es enlazar el comentario correspondiente.
finalmente, en mensajes de commit como [este](https://github.com/danigonzser/proyecto-tfg/pull/12/commits/7d9010d627755a98692388e37da6bf1d5687e0eb) no sigues las buenas prácticas de 50 caracteres en la primera línea, por eso aparece cortado y no se puede ver de un primer vistazo qué hace.

2024-02-07 12:13 UTC, danigonzser commented
Vale, referenciaré los issues de ahora en adelante y acortaré los commits. Gracias

2024-02-07 12:16 UTC, JJ requested changes
De todas las soluciones, trata de escoger la más simple. Ánimo que ya queda menos.

2024-02-07 12:16 UTC, JJ commented on .github/workflows/latex.yml
> +      doc_changed: ${{ steps.check_changes.outputs.doc_changed }}
¿Has probado a ver si se puede conseguir lo mismo simplemente usando `paths` en el comando `on`?

2024-02-07 12:16 UTC, JJ commented on .github/workflows/latex.yml
> +          fetch-depth: 0
En bases grandes de código, puede haber cierta diferencia de velocidad entre esto y el valor por omisión (que no sé si es 1, habría que mirarlo)

2024-02-07 12:16 UTC, JJ commented on .github/workflows/latex.yml
> +      - id: check_changes
Por favor, mira a ver si se puede hacer esto de una forma más simple poniendo, como te digo más arriba, una simple orden en la configuración que impida que se lance si no se han cambiado los ficheros.
Antes de usar generadores de código tipo GitHub Pilot (que ayudan mucho) conviene que mires un simple manual de referencia. El de GitHub actions es bastante bueno y lo explica todo con bastante ejemplos.

2024-02-07 12:16 UTC, JJ commented on .github/workflows/latex.yml
> +    needs: [ check_if_docs_has_changed ]
Todo esto está bien, has aprendido a secuenciar jobs, a crear variables de job, y todo eso. Ahora olvídate por el momento y trata de resolverlo de la forma más simple posible.

2024-02-07 12:16 UTC, JJ commented on .github/workflows/latex.yml
> +    runs-on: ubuntu-latest
Aparte de que estás usando dos jobs, y para que se ejecute algo después de otro simplemente ejecútalos como steps. En el momento que falle un step, ya no se ejecutan los siguientes. De esta forma estás provisionando dos runners, haciendo checkout dos veces y en general ralentizando los tests (que deben ser FIRST, donde la F es Fast)

2024-02-07 18:40 UTC, merged