Terminada la introducción
danigonzser/proyecto-tfg pull request #14
Opened 2024-02-06 18:47 UTC by danigonzser

En ella se escribe la motivación, descripción del problema y los objetivos.

2024-02-06 18:51 UTC, JJ requested changes
Algunos cosas que debes considerar
1. La frase de introducción es demasiado genérica, podría servir para el 80% de los TFGs
2. Hay que ser Consistente en El uso de Mayúsculas en Los títulos De secciones.

Cuando vea el contenido te digo. Sólo que tengas en cuenta cuál es el objetivo de esta introducción, principalmente dirigida al tribunal, y trates de cubrirlo lo mejor posible.

2024-03-13 09:53 UTC, danigonzser commented
listo para revisión @JJ

2024-03-13 10:05 UTC, JJ commented
Resuelve los conflictos antes, por favor.

2024-03-13 17:19 UTC, danigonzser commented
@JJ conflictos resueltos

2024-04-02 08:50 UTC, JJ commented
Parece que todavía tiene conflictos, ¿no?

2024-04-02 17:08 UTC, danigonzser commented
> Parece que todavía tiene conflictos, ¿no?

Ya están resueltos los conflictos @JJ

2024-04-02 18:00 UTC, JJ requested changes
La necesidad de definir "personas" es simplemente definir diferentes clientes que vayan a usar la aplicación, con diferentes necesidades a cubrir pero también capacidades cognitivas. Si defines 6 o 7 personas, cada una debería tener una historia de usuario diferenciada y tendrías que ser capaz de abordarlas. Por ello es conveniente que lo hagas un poco en paralelo: crea una persona, luego una historia de usuario correspondiente. Recuerda que esta metodología, como todas las demás, no es un fin en si, no se trata de probar si tienes imaginación para crear 2 o 3 o 40 personas, sino de que eres capaz de visualizar quién va a usar tu aplicación y de qué forma tienen necesidades diferentes.

2024-04-02 18:00 UTC, JJ commented on doc/secciones/01_intro.tex
> +Si la respuesta es sí y que después de estar guardando contenido en su solución de almacenamiento elegida durante un tiempo, se vuelve insostenible y ya no es nada útil, el problema que se propone re
De esto yo entiendo que lo que vas a hacer es un buscador de imágenes, posiblemente con IA. Y creo que  no se trata de eso.
El poblema principal es que no has hecho las historias de usuario. Realmente hasta que no acabes la introducción no hacen falta, pero la idea que yo tengo, de trabajar con memes, no tiene que ver con esto realmente.

2024-04-08 17:10 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-08 18:27 UTC, JJ commented
Por favor, recuerda que los cuerpos de los PRs deben tener *siempre* los issues que está tratando de resolver. Sin ellos, es imposible saber si lo que se está haciendo es correcto.

2024-04-08 18:34 UTC, JJ requested changes
He abierto #28 para que aclares cuales van a ser los objetivos generales del TFG.

2024-04-08 18:34 UTC, JJ commented on doc/secciones/01_intro.tex
> +Si la respuesta es sí y que después de estar guardando contenido en su solución de almacenamiento elegida durante un tiempo, se vuelve insostenible y ya no es nada útil, el problema que se propone re
También, cuando solicites revisión, resuelve todos los comentarios cambiando la línea en la que están o indicando en qué commit que modifica otra línea se han resuelto.

2024-04-08 18:34 UTC, JJ commented on doc/secciones/01_intro.tex
> +                \item \textbf{¿Qué le gustaría que tuviera?}: Le gustaría que no tuviera complicaciones a la hora de la instalación y configuración. Todas las facilidades que ya le brinda Microsoft O
De veras que no acabo de ver lo que estás haciendo aquí. Insistes en hablar de un sistema de almacenamiento. ¿Es eso lo que quieres hacer?

2024-04-09 17:58 UTC, JJ requested changes
Ha mejorado bastante, pero quizás puedes avanzar un poco más en la misma dirección.

2024-04-09 17:58 UTC, JJ commented on doc/secciones/01_intro.tex
> +La motivación detrás de este proyecto radica en ofrecer una solución que resuelva problemas y satisfaga las necesidades de diversos usuarios en diferentes contextos. El proyecto `Memes para todos` as
¿Qué problemas?

2024-04-09 17:58 UTC, JJ commented on doc/secciones/01_intro.tex
> +\section{Milestones}
¿no crees que los milestones deberían estar mejor en la metodología?
En todo caso, en desarrollo ágil solo se plantearían los milestones iniciales; los siguientes son parte de la implementación.

2024-04-09 17:58 UTC, JJ commented on doc/secciones/01_intro.tex
> +Los memes se han convertido en un lenguaje universal en el mundo digital, traspasando fronteras, culturas y generaciones. Desde las conversaciones informales en grupos de chat, hasta en las estrategi
¿Quizás podrías expandir un poco más? ¿En qué casos se puede necesitar un meme? ¿Presentaciones de trabajos de clase? ¿Compartir en redes sociales? 
Este párrafo tiene que comprártelo #2 ¿Crees que con esta descripción te lo va a comprar?

2024-04-10 07:32 UTC, JJ requested changes
Considera poner los objetivos iniciales con la abstracción suficiente para que se puedan meter en esta fase, hablando de que la solución "pueda ser adoptada por cualquier organización (es decir, que sea software libre)", "comprenda una gama de clientes lo más amplia posible" (es decir, que haya una solución ejecutándose en la web y la gente pueda instalársela, aunque esto solo si te preguntan, se trata de formular objetivos vagos), "que sea lo más económica posible" (una solución que se pueda instalar uno en un servidor en la oficina o desplegar en un contenedor).
En resumen, que se trata de objetivos de alto nivel y si me apuras sin ninguna relación con el proyecto en si.

2024-04-10 07:32 UTC, JJ commented on doc/secciones/01_intro.tex
> +De las historias de usuario y personas identificadas se han extraído los siguientes objetivos iniciales:
No has incluido las historias de usuario. Hasta que no las incluyas no puedes poner estos objetivos iniciales. Estos objetivos deben ser suficiente vagos para poder ser iniciales. Los objetivos concretos se verán durante el proceso de desarrollo.

2024-04-10 16:40 UTC, danigonzser commented on doc/secciones/01_intro.tex
> +De las historias de usuario y personas identificadas se han extraído los siguientes objetivos iniciales:
Las historias de usuarios se han incluído en #26

2024-04-10 17:25 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-11 09:14 UTC, JJ requested changes
El principal problema es mencionar aquí algo (historias de usuario) de lo que vas a hablar más adelante. El resto no bloquea, pero sería interesante que lo consideraras.

2024-04-11 09:14 UTC, JJ commented on doc/secciones/01_intro.tex
> +Imagine una escena en la que un grupo de amigos se reúne y discuten sobre los últimos acontecimientos políticos cuando, de repente, un meme ingenioso y fuera de lugar se convierte en el centro de la
¿No has pensado usar ejemplos más cercanos? ¿Un estudiante presentando un trabajo, un profesor presentando en un congreso, un profesional presentando en un grupo de usuarios?

2024-04-11 09:14 UTC, JJ commented on doc/secciones/01_intro.tex
> +De las historias de usuario y personas identificadas se han extraído los siguientes objetivos iniciales:
Si ese es el caso, no puedes hablar de ellas aquí. No puedes decir que has extraído nada de algo de lo que no se ha hablado todavía.

2024-04-16 16:06 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-16 17:34 UTC, JJ approved these changes
Agh, no, Chema Alonso no, por favor...

2024-04-16 21:20 UTC, danigonzser commented
Ahora sí que sí @JJ .

2024-04-17 08:08 UTC, JJ commented
Estaba aprobado, puedes fusionarlo cuando quieras.

2024-04-17 08:09 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \caption{Pierde el miedo a desplegar a producción en viernes de \href{https://midu.dev/}{Miguel Ángel Durán} y \href{https://platzi.com/}{Platzi}en \href{https://platzi.com/conf/}{Platzi Conf} \c
Las imágenes no se acreditan así; tienes que poner quién es el autor y la licencia. Si  no tienen licencia libre, indica el (c) de la imagen y la fuente.

2024-04-17 08:10 UTC, JJ commented on doc/secciones/01_intro.tex
> +
Trata también de poner siempre un poco de narrativa antes de cada lista y al principio de cada sección.

2024-04-17 08:11 UTC, JJ requested changes
Pensándolo bien, quizás tengas que darle una vuelta.

2024-04-17 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +Dentro de este marco de trabajo, para realizar una mejor de definición del problema, se han identificado una serie de personas con necesidades y objetivos específicos que junto con las historias de u
Y esto se ha quedado un poco descolgado, creo. ¿Todavía hace falta aquí?

2024-04-17 18:57 UTC, danigonzser commented on doc/secciones/01_intro.tex
> +Dentro de este marco de trabajo, para realizar una mejor de definición del problema, se han identificado una serie de personas con necesidades y objetivos específicos que junto con las historias de u
Cambiado en #26

2024-04-17 18:58 UTC, danigonzser commented
Listo para revisión @JJ .

2024-04-18 08:19 UTC, JJ reviewed
He estado echando un vistazo al vídeo y no tiene información específica sobre autoría ni sobre licencia, así que hay que asumir que la autoría es de Platzi (no de Miguel Ángel Durán) y que el vídeo tiene todos los derechos reservados. Puedes incluir clips de un vídeo invocando el derecho de cita, pero tienes que hacerlo explícitamente. Tendrías que poner preferiblemente el enlace corto, indicar la fuente, autoría y licencia, en este y en todos.

2024-04-18 08:19 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \caption{Fotograma sacado del vídeo de YouTube de la conferencia:  \cite{confe}.}
Creo que sigues confundiendo la cita con la acreditación de la ilustración. La acreditación de la ilustración tiene que incluir autoría y licencia, *nunca* es una cita (y si es una cita, un canal o vídeo de YouTube no se cita aquí).

2024-04-18 18:26 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-18 18:32 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \caption{Fotograma sacado del (\href{http://sl.ugr.es/0dXQ}{vídeo de YouTube de la conferencia}): Pierde el miedo a desplegar a producción en viernes | ft @midudev. Vídeo realizado por Platzi par
Tienes que poner el (c) explícitamente. Cambia "realizado por Platzi" por (c) Platzi

2024-04-18 18:40 UTC, danigonzser commented on doc/secciones/01_intro.tex
> +    \caption{Fotograma sacado del (\href{http://sl.ugr.es/0dXQ}{vídeo de YouTube de la conferencia}): Pierde el miedo a desplegar a producción en viernes | ft @midudev. Vídeo realizado por Platzi par
Listo

2024-04-18 23:02 UTC, danigonzser commented
Como he cambiado de base de la rama `m0/estado-del-arte` se han modificado algunos archivos a una versión anterior como README.md, doc/bibliografia.bib y doc/secciones/03_estado_del_arte.tex.  Éstos han sido revertidos a su versión que tenían en la rama m0/introduccion donde aprobaste todos los cambios. Como se han modificado ciertas cosas (aunque espero que no hayan cambios) solicito una última revisión @JJ . Muchas gracias

2024-04-19 08:31 UTC, JJ approved these changes
No me siento capaz de revisarlo todo de nuevo. Si acaso al final del milestone le damos un repaso más general.

2024-04-22 16:40 UTC, merged