Estructura inicial temporal finalizada
danigonzser/proyecto-tfg pull request #16
Opened 2024-02-13 18:10 UTC by danigonzser

2024-02-14 10:36 UTC, JJ commented
Convendría que pusieras *siempre* una descripción en el PR para ver su ámbito y con qué issues se está trabajando. Si no, es imposible saber si lo que está es correcto o no.

2024-02-14 10:39 UTC, JJ requested changes
Aparte del comentario hecho, estas son mis impresiones.

2024-02-14 10:39 UTC, JJ commented on doc/proyecto.tex
> +	% Tests y despliegue
En todo caso, si se trata de ver la estructura, yo no pondría los capítulos en este fichero hasta que no se creen por otro lado. ¿Crees que aporta algo tenerlos ya aquí antes de escribirlos?

2024-02-14 10:39 UTC, JJ commented on doc/secciones/06_tests_despliegue.tex
> +\chapter{Tests y despliegue}
Por lo mismo, este capítulo y los siguientes no tendría mucho sentido crear una estructura hasta que se necesiten, y más bien si se necesitan.

2024-02-14 10:39 UTC, JJ commented on doc/secciones/09_conclusiones.tex
> +\chapter{Conclusiones}
Un capítulo de conclusiones siempre se suele hacer, pero el nombre del fichero y la estructura interna no tiene por qué ser esa. En general, suele ser un capítulo corto, sin secciones. Pero en todo caso hasta que no haga falta meterlo aquí no parece que ayude, por lo pronto, a #2 , ¿no?

2024-02-14 11:11 UTC, danigonzser commented
@JJ listo para revisión.

2024-02-15 07:33 UTC, JJ approved these changes
:+1:

2024-02-15 10:15 UTC, merged