Añadidas historias de usuario de las "personas"
danigonzser/proyecto-tfg pull request #26
Opened 2024-03-21 13:31 UTC by danigonzser

Tras meditarlo, sí he decidido incluir a Laura Martínez ya que aporta una historia de usuario importante.

2024-03-21 13:36 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-02 16:51 UTC, danigonzser commented
Ya está enlazada la issue @JJ

2024-04-02 18:02 UTC, JJ commented
No estás definiendo historias de usuario, sino usuarios en sí. Las historias de usuario expresan los deseos de los usuarios, qué problema quieren que les solucionen. En [este artículo](https://www.linkedin.com/pulse/los-issues-y-su-importancia-en-la-organizaci%25C3%25B3n-de-un-proyecto-merelo/?trackingId=snKNI3haQJCx4x9Q2Lod%2Fg%3D%3D) te cuenta cómo son las historias de usuario y como expresarlas.

2024-04-02 18:05 UTC, JJ reviewed
Creo que más allá de usar lo de alguna asignatura que hayas hecho, que no parece que contribuya a avanzar la aplicación, deberías tratar de entender mejor cómo formular las historias de usuario (ligándolas con las características específicas de cada *persona*)

2024-04-02 18:05 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \item Como María Rodríguez, quiero poder acceder a la aplicación desde mi ordenador portátil, teléfono móvil y tablet en cualquier momento.
Esto no es una historia de usuario. La HU se expresa en el dominio del problema y no implica ninguna solución. Esta frase no dice nada sobre el problema, por lo que podría resolverse de cualquier forma y con cualquier lógica de negocio.

2024-04-02 18:05 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \item Como María Rodríguez, necesito algún tipo de búsqueda avanzada para encontrar cualquier meme ya sea por título, etiquetas o contenido del propio meme.
Una vez más, estás hablando de una solución, no de un problema. Mira en el [objetivo 1 de la asignatura IV](http://jj.github.io/IV/documentos/proyecto/1.Planificacion) cómo se formulan las historias de usuario.

2024-04-08 17:10 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-11 08:38 UTC, JJ commented on doc/secciones/01_intro.tex
> +    María Rodríguez Espinosa es una creadora de contenido especializada en memes. Trabaja actualmente para una famosa cadena de comida rápida. Su objetivo principal es mantener comprometida a su audi
¿Eso existe?

2024-04-11 08:40 UTC, JJ commented on doc/secciones/01_intro.tex
> +    Carlos Sánchez es el propietario de un pequeño negocio local especializado en la venta de comida rápida. Inspirado por la exitosa estrategia de KFC de posicionarse como una marca influencer en la
Las *personas* no son simplemente una acumulación de descripciones. Son clientes que hay que satisfacer, con necesidades específicas, bien en lógica de negocio, bien en modo de presentación de la aplicación. De sus descripciones hay que extraer historias de usuario, que son los que van a guiar el desarrollo de la aplicación. ¿Qué necesidades específicas crees que tiene este cliente en ese sentido, y en qué es diferente del resto?

2024-04-11 08:41 UTC, JJ commented on doc/secciones/01_intro.tex
> +        \item [HU01] Como María Rodríguez, creadora de contenido de memes para KFC, necesito poder editar memes y almacenarlos.
No estás expresando un problema. Como el problema no es específico, la solución también sería inespecífica: usa un programa de dibujo y mételos en un pendrive, por ejemplo. Para eso no hace falta un aplicación siquiera.

2024-04-16 16:07 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-17 08:30 UTC, JJ requested changes
Ha mejorado bastante y creo que en general reflejan el espíritu del concepto de historia de usuario, pero sería conveniente que revisaras cosas que te has dejado de la versión anterior y definieras un poco más las necesidades específicas de cada *persona* (quitando además las que se salgan de ámbito)

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +    Cristina Contreras Márquez es una estudiante de ingeniería informática qué, como cualquier otro estudiante necesita hacer presentaciones para exponer sus trabajos. Cristina es una persona creativ
qué no lleva acento aquí. ¿Estás usando el comprobador gramatical?

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +    Ted Johnson González es un experto en dialéctica que realiza muchas ponencias y charlas. Ted es un ponente profesional que siempre busca la forma de hacer sus charlas más amenas y entretenidas. L
¿Experto en dialéctica? Sera oratoria, ¿no?

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \subsubsection{Ted Johnson González (experto conferenciante)}
Las *personas* que incluyas aquí deben expresar diferentes necesidades y tener diferentes problemas. Si no entiendes de antemano qué problema tienen y en qué son diferentes de los anteriores, no los crees. En este específicamente veo varias características que podían ser problemas únicos, pero no tengo tan claro que tú lo veas de la misma forma.

La única forma de ver si efectivamente es así, son diferentes o no es que pongas las historias de usuario en el mismo PR que la descripción de las personas, creo. No sé si lo habrás hecho, sigo leyendo.

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +    El departamento de marketing de `Corporate Solutions` le ha expresado al CTO en la empresa, la necesidad de un sistema centralizado para agilizar el proceso de generación y gestión de multimedia
La multimedia de un departamento de márketing es muy extensa, y no sé si los memes se incluirán o no.
En general, siguiendo la filosofía de *design thinking*, si no tienes empatía (que viene del conocimiento personal) con un cliente, es mejor que lo evites. 
Igual que te digo arriba, no tengo muy claro qué problema específico se puede sacar de aquí también. Tendría que ver la historia de usuario.

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU02] Como María Rodríguez, estudiante de Ingeniería Informática, me gustaría poder elegir entre una serie de memes predefinidos o hechos por mí para poder añadirlos a mis presenta
María ya no está.

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU01] Como Cristina Contreras Márquez, estudiante de Ingeniería Informática, desearía un sistema donde poder ir confeccionando memes a partir de plantillas (para hacerlos más rápid
La historia de usuario no puede incluir ningún tipo de solución, como en este caso las plantillas.

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU03] Como Ted Johnson González, experto conferenciante, necesito un sistema que me permita encontrar memes relevantes y atractivos para incluir en mis presentaciones.
¿En qué es diferente de la HU02?

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU04] Como Ted Johnson González, experto conferenciante, necesito una herramienta que me permita personalizar y adaptar los memes a mi estilo y contenido.
¿En qué es diferente de la HU01?

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU05] Como departamento de marketing, nos gustaría tener un sistema centralizado que nos permita de forma centralizada generar y gestionar multimedia.
¿Crees que esto tiene algo que ver con la gestión de memes?

2024-04-17 08:30 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU06] Como departamento de marketing, necesitaríamos una herramienta que nos permita colaborar en un meme varios miembros del equipo.
OK, esto es como me lo imaginaba. Me parece razonable, y sería específico para este usuario.

2024-04-17 18:35 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-18 08:11 UTC, JJ requested changes
El principal problema es estilístico, pero también de comentarios que has resuelto sin indicar por qué. Las HUs han mejorado y están más centradas, pero todavía cuesta diferenciar entre ellas.

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +
Este comentario no está resuelto. Sigue sin haber una introducción.

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \subsubsection{Ted Johnson González (experto conferenciante)}
Tampoco lo has resuelto. Si es así, debes indicar en qué commit se ha hecho.

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +    El departamento de marketing de `Corporate Solutions` le ha expresado al CTO en la empresa, la necesidad de un sistema centralizado para agilizar el proceso de generación y gestión de multimedia
Sigues poniendo el tema de multimedia, que no tiene nada que ver con el ámbito del proyecto. Tampoco es que los memes sean multimedia, pero conviene que te centres en lo que concierne al proyecto.

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \subsection{Cristina Contreras Márquez (estudiante de ingeniería informática)}
Esta sección tampoco tiene una introducción. Aunque sea redundante, tienes que indicar de dónde se viene, qué papel ocupa este contenido en el capítulo y en el proyecto, y cómo va a estar organizado. ¿Crees que #2 sabe lo que son las historias de usuario, o lo que son *en este contexto*? ¿Crees que conoce por qué son imprescindibles dentro de un desarrollo ágil?

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU02] Como Cristina Contreras Márquez, estudiante de Ingeniería Informática, me gustaría poder elegir entre una serie de memes predefinidos o hechos por mí para poder añadirlos a m
"Poder elegir" es una solución, no un problema. Las HUs siempre son problems. ¿Por qué quiere elegir?

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU01] Como Cristina Contreras Márquez, estudiante de Ingeniería Informática, desearía un sistema donde poder ir confeccionando memes a medida que se me van ocurriendo mientras elab
Ir confeccionándolos "a medida de que" da la idea de que los necesita rápidamente. ¿Es así?

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU03] Como Ted Johnson González, experto conferenciante, necesito un sistema que me permita encontrar memes relevantes y atractivos que no tienen por qué estar creados por mí para
¿En qué se diferencia de HU02? Además, "permitir encontrar" es una solución, no un problema.

2024-04-18 08:11 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU06] Como departamento de marketing, necesitaríamos una herramienta que nos permita colaborar en un meme varios miembros del equipo.
... pero ahora no hay ninguna diferencia con HU05

2024-04-18 18:11 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-18 18:14 UTC, JJ requested changes
No veo la diferencia entre las dos historias de usuario señaladas. Por favor, aclárala o suprime una de ellas.

2024-04-18 18:14 UTC, JJ commented on doc/secciones/01_intro.tex
> +            \item [HU04] Como Ted Johnson González, experto conferenciante, quiero que, tras encontrar un meme, me permita personalizarlo y adaptarlo a mi estilo y contenido.
¿En qué es esto diferente a HU02?

2024-04-22 17:16 UTC, danigonzser commented
Listo para revisión @JJ .

2024-04-23 06:57 UTC, JJ commented on doc/secciones/01_intro.tex
> +
Esto sigue sin estar resuelto.

2024-04-23 06:58 UTC, JJ commented on doc/secciones/01_intro.tex
> +    \subsubsection{Ted Johnson González (experto conferenciante)}
Por favor, no resuelvas sin al menos indicar dónde se ha resuelto, si es que no has cambiado la línea donde estaba.

2024-04-23 07:03 UTC, JJ requested changes
Por favor, no resuelvas los comentarios "en falso", indica qué se ha hecho para resolverlos con referencia a commits específicos. Si no, es imposible saber qué se ha hecho al respecto. Por otro lado, sería conveniente que no insistieras en volver a poner las mismas HU una y otra vez, sino que intentaras o diferenciarlas extendiendo la descripción o el contexto o simplemente eliminando alguna. Te recuerdo que no hay un número mínimo de historias de usuario.

2024-04-23 18:09 UTC, danigonzser commented
Listo para revisión @JJ

2024-04-23 18:11 UTC, JJ commented
Por favor, no pongas la resolución a los comentarios en el cuerpo. La idea es que se pongan en el mismo comentario, es lo más simple para poder ver cómo se ha resuelto.

2024-04-23 18:15 UTC, JJ approved these changes
No vamos a darle más vueltas, pero ten  en cuenta el último comentario, por favor.

2024-04-23 18:15 UTC, JJ commented on doc/secciones/01_intro.tex
> +La identificación de los usuarios es un paso fundamental para el desarrollo del proyecto, ya que permite definir mejor las necesidades, requisitos, deseos, expectativas del usuario final que hará emp
¿No crees que esto estaría mejor como introducción de la subsección, que sigue sin tener una? Recuerda que todo apartado debe tener una introducción, sea capítulo, sección o subsección.

2024-04-24 18:55 UTC, merged