Capítulo de análisis
danigonzser/proyecto-tfg pull request #40
Opened 2024-06-21 20:23 UTC by danigonzser

En este capítulo se va a llevar a cabo el análisis mediante DDD.

2024-06-24 17:37 UTC, danigonzser commented
Arreglados fallos. Listo para revisión @JJ

2024-06-25 19:55 UTC, danigonzser commented
Sigo avanzando. Listo para revisión @JJ.

2024-06-26 06:19 UTC, JJ commented
Acostúmbrate a mencionar en cada PR los issues con los que estás trabajando, con closes #xx delante si los soluciona. Si no se sabe con qué issues se está trabajando, no se sabe como añade valor al cliente, y por tanto es imposible de revisar.

2024-06-26 18:43 UTC, danigonzser commented
Issues enlazados @JJ

2024-07-16 07:15 UTC, JJ requested changes
Realmente soy escéptido sobre los análsiis teóricos, lejos del código, que al final pueden o no ser útiles, sobre todo si acabas aplicando cosas de forma subóptima y no producen el código deseado. DDD debe producir código, las estructuras de datos básicas sobre las que va a trabajar. Si no lo hace (y en el mismo PR), ¿no te parece que falla algo?
En general, lo que debes buscar es identificar los objetos valor para empezar y programarlos. Para identificar los objetos valor se hacen una serie de issues que vayan acotando los subdominios que van a modelizar cada uno de esos objetos valor y finalmente se crea la estructura de datos. Idealmente debería haber un PR por cada estructura de datos, pero si al final sólo hay una o dos podrían ir en el mismo PR.
Al ser también el primer PR que incluye código, sería conveniente incluir también infraestructura para comprobar la calidad del código: linters, por ejemplo.

2024-07-16 07:15 UTC, JJ commented on doc/secciones/05_analisis.tex
> +    \item \textbf{Almacenamiento}: este dominio englobaría toda la parte de la persistencia de memes.
Esto no está en el dominio del problema.

2024-07-16 07:15 UTC, JJ commented on doc/secciones/05_analisis.tex
> +    \item \textbf{Gestión de usuarios}: es una parte fundamental para permitir la colaboración en la creación y edición de memes. Además, manejaría la creación, administración, autenticación, privile
No está en el dominio del problema.

2024-07-16 07:15 UTC, JJ commented on doc/secciones/05_analisis.tex
> +    \item \textbf{Edición}: abarcaría todas las funcionalidades relacionadas con la creación y modificación de memes.
Realmente no es un dominio ni subdominio, sino una serie de tareas que se llevarán a cabo sobre un meme, ¿no?

2024-07-16 07:15 UTC, JJ commented on doc/secciones/05_analisis.tex
> +    \item \textbf{Búsqueda}: al ser una de las funcionalidades principales, se ha decidido que sea un subdominio. Se encargaría de toda la parte de la búsqueda avanzada de memes mediante diferentes c
Tampoco es un subdominio, es una tarea.

2024-07-24 11:07 UTC, JJ approved these changes
OK, no le demos más vueltas. Lo de los requisitos le gusta a ciertos miembros del tribunal, aunque realmente en desarrollo ágil es algo que tiene que surgir del análisis del próximo producto mínimamente viable, aparte de ser obvios a partir de las HUs.

2024-07-26 10:29 UTC, merged