Cap
danigonzser/proyecto-tfg pull request #46
Opened 2024-07-09 19:54 UTC by danigonzser

2024-07-09 20:02 UTC, danigonzser commented
Listo para revisión @JJ

2024-07-10 06:16 UTC, JJ requested changes
Por favor, considera cada sección y subsección por separado a la hora de integrarlo o no en un capítulo. Trata de limitar el capítulo a lo que efectivamente titula.

2024-07-10 06:16 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\section{Enfoque Ágil}
¿Seguro que vas a Usar mayúsculas en Los títulos de Sección?

2024-07-10 06:16 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\section{Entrega y calidad continua}
Aquí no lo estás usando

2024-07-10 06:16 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +    \item \textbf{¿Se está usando enfoques ágiles?} El informe indica que los enfoques ágiles son ampliamente utilizados en la industria del software, permitiendo a los equipos de desarrollo trabajar
¿Esto no te lo ha pillado el corrector gramatical?

2024-07-10 06:16 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\subsection{Corrector ortográfico y gramatical}
El que vayas a usar unas herramientas parece que sí es parte de la metodología. ¿Las herramientas específicas que uses, no serán parte de la implementación?

2024-07-10 06:16 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +El uso de un corrector ortográfico y gramatical en un texto de alta calidad es esencial para lograr claridad y profesionalismo en la comunicación escrita. No se trata solo de evitar errores ortográfi
Este párrafo me suena a generado por ChatGPT. ¿De veras crees que aporta algo? También el título, ¿qué significa?

2024-07-10 06:16 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\subsubsection{Herramientas seleccionadas}
¿la selección de herramientas no sería parte de la implementación?

2024-07-11 18:47 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +\section{Entrega y calidad continua}
No entiendo este comentario.

2024-07-11 18:50 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +\subsubsection{Herramientas seleccionadas}
Sí, he dejado la selección de herramientas para una posterior fase en la implementación.

2024-07-11 18:50 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +El uso de un corrector ortográfico y gramatical en un texto de alta calidad es esencial para lograr claridad y profesionalismo en la comunicación escrita. No se trata solo de evitar errores ortográfi
Apunto este comentario para cuando tratemos la selección de herramientas en la implementación.

2024-07-11 18:51 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +\subsection{Corrector ortográfico y gramatical}
Sí es verdad. He movido toda esa parte a la parte en la que se trata la implementación.

2024-07-11 18:52 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +    \item \textbf{¿Se está usando enfoques ágiles?} El informe indica que los enfoques ágiles son ampliamente utilizados en la industria del software, permitiendo a los equipos de desarrollo trabajar
No me lo había pillado ninguno de los dos correctores. Raro. Arreglado en 11b5dd8.

2024-07-11 18:52 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +\section{Enfoque Ágil}
Arreglado en 11b5dd8.

2024-07-11 18:55 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\section{Entrega y calidad continua}
Se ha quedado descolgado. Quería decir que no estás usando mayúsculas fuera de la primera letra.

2024-07-11 18:59 UTC, JJ requested changes
Por favor, cuando te haga un comentario no mires exclusivamente la línea donde está hecha, sino el resto del texto y mira a ver si se aplica.

2024-07-11 18:59 UTC, JJ commented on doc/secciones/04_metodologia.tex
> +\subsection{Extensión de \textit{Visual Studio Code}: \textit{LaTeX Workshop}}
De veras, mira todo lo que queda a ver si realmente corresponde a la metodología, que es lo de este capítulo. ¿Que hayas usado una extensión para latex es parte de la metodología?

Todavía git puedes decir que es una metodología basada en los flujos de trabajo y control de fuentes, pero ninguna herramienta es parte de la metodología. La metodología tiene que incluir buenas prácticas para elegir herramientas, y las herramientas se eligen como parte de la implementación.

2024-07-11 19:29 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +\section{Entrega y calidad continua}
Vale, ya lo entiendo. Perfecto gracias

2024-07-11 19:40 UTC, danigonzser commented on doc/secciones/04_metodologia.tex
> +\subsection{Extensión de \textit{Visual Studio Code}: \textit{LaTeX Workshop}}
Las próximas veces estaré más atento en cuanto a lo que me comentas no solo limitandome a las líneas. Dentro de mi cabeza casan ciertas cosas que no deberían de casar. Arreglado en e938671.

2024-07-11 19:41 UTC, danigonzser commented
Listo para revisión @JJ

2024-07-12 06:11 UTC, JJ approved these changes
Una vez más, al principio del capítulo y en partes prominentes escribe qué rúbricas pretendes cubrir con el contenido de este capítulo.

2024-07-15 19:07 UTC, danigonzser commented
He añadido alguna referencia a la rúbrica @JJ

2024-07-16 06:34 UTC, JJ commented
Está aprobado, puedes fusionarlo cuando quieras.

2024-07-16 19:26 UTC, merged