Estructura base personalizada acabada
danigonzser/proyecto-tfg pull request #6
Opened 2024-01-19 18:42 UTC by danigonzser

Se han añadido secciones a introducción análisis y a estado del arte y diseño. Se ha eliminado INSTALL.md de la plantilla y se ha modificado la plantilla para personalizarla. Adjunto foto del índice hasta el momento.
![Índice general actual](https://github.com/danigonzser/proyecto-tfg/assets/21023099/86814f1e-0d03-46d0-878f-c7ac6f62caf5)

2024-01-19 19:05 UTC, JJ requested changes
El principal problema que veo aquí es el capítulo 5. Pero hay otros temas que habría que resolver antes de fusionar este PR. Voy a abrir otros issues para indicarlo.

2024-01-19 19:05 UTC, JJ commented on doc/secciones/05_analisis.tex
> +\section{Análisis de las soluciones}
El primera problema es que en desarrollo ágil, no hay un "análisis del problema" y menos como una fase diferenciada de la modelización del mismo. Se aplica domain driven design o alguna metodología similar para mapear el problema al código, pero eso es parte de la implementación. El pre-análisis del problema, ver en qué consiste y quién tiene ese problema, es parte de la introducción más bien.

2024-01-19 19:05 UTC, JJ commented on doc/secciones/03_estado_del_arte.tex
>  El software libre y sus licencias \cite{gplv3} ha permitido llevar a cabo una expansión del
El software libre es principalmente un aspecto legal, no tanto del estado del arte. Pero se decide la licencia cuando se empieza a implementar, así que sería parte de la implementación.

2024-01-21 13:39 UTC, danigonzser commented on doc/secciones/05_analisis.tex
> +\section{Análisis de las soluciones}
Modificaré la parte que comentas. Voy a adaptar más la introducción y los sucesivos capítulos. No había tenido en cuenta muchos los otros caps.

2024-01-21 13:40 UTC, danigonzser commented on doc/secciones/03_estado_del_arte.tex
>  El software libre y sus licencias \cite{gplv3} ha permitido llevar a cabo una expansión del
Lo arreglo.

2024-01-22 12:46 UTC, danigonzser commented
Nueva estructura de la memoria.
![Estructura](https://github.com/danigonzser/proyecto-tfg/assets/21023099/888ebbb1-f523-4c3e-bf27-4d378aa980be)

2024-04-16 21:53 UTC, danigonzser commented
En cuanto a esto, solo contiene limpieza y el readme.md actualizado y bien hecho. ¿Debería de borrar esto e incorporarlo a otra rama? @JJ

2024-04-18 22:06 UTC, merged